default_pulling_interval: 1
token: C7F6SrCYROw6XsHSSSjYKaJgheRza8lgWWOQuhPQ
plugins:
  - type: postgresql
    name: AEG-test
    host: !ENV {SAMPLE_POSTGRES_HOST}
    port: 5432
    database: !ENV {SAMPLE_POSTGRES_DATABASE}
    user: !ENV {SAMPLE_POSTGRES_USER}
    password: !ENV {SAMPLE_POSTGRES_PASSWORD}