name: Branch Build
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  images:
    runs-on: self-hosted
    env:
      REGISTRY: 436866023604.dkr.ecr.eu-central-1.amazonaws.com
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: unfor19/install-aws-cli-action@v1
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1.3.3
      - name: Cache local node_modules
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-platform-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-platform-
      - name: Set up JDK 13
        uses: actions/setup-java@v2
        with:
          java-version: '13'
          distribution: 'adopt'
      - name: Build with Gradle
        env:
          NODE_ENV: production
          GENERATE_SOURCEMAP: false
          CI: false
          JAVA_OPTS: "-Xms2048m -Xmx2048m"
        run: ./gradlew jibDockerBuild --no-daemon -PoddGHPRepositoryUsername=github-actions -PoddGHPRepositoryPassword=${{ secrets.GITHUB_TOKEN }} --image ${{ env.REGISTRY }}/${{ github.event.repository.name }} -Pversion=ci-${GITHUB_SHA::6}
      - name: Push Docker image to Amazon ECR
        run: docker push ${{ env.REGISTRY }}/${{ github.event.repository.name }}:ci-${GITHUB_SHA::6}
  update_tag:
    needs: ["images"]
    runs-on: self-hosted
    steps:
      - name: Masking token
        run: |
          INP_GIT_TOKEN=$(echo ${ODD_GIT_TOKEN} | base64 -d)
          echo ::add-mask::$INP_GIT_TOKEN
          echo MASKED_ODD_GIT_TOKEN="$INP_GIT_TOKEN" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          repository: provectus/environment-state
          token: ${{ env.MASKED_ODD_GIT_TOKEN }}
      - run: |
          sed -i "s/tag:.*/tag: ci-${GITHUB_SHA::6}/" odd-platform.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit --allow-empty -m "update tag"
          git push
